'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Brickstream_Camera_Utility.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brickstream_logo() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brickstream_logo", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 192.168.1.10
        '''192.168.1.11
        '''192.168.1.12
        '''192.168.1.13
        '''192.168.1.14
        '''192.168.1.15
        '''192.168.1.16
        '''192.168.1.17
        '''192.168.1.18
        '''192.168.1.19
        '''192.168.1.20
        '''192.168.1.21
        '''192.168.1.22
        '''192.168.1.23
        '''192.168.1.24
        '''192.168.1.25
        '''192.168.1.26
        '''192.168.1.27
        '''192.168.1.28
        '''192.168.1.29
        '''192.168.1.30
        '''192.168.1.31
        '''192.168.1.32
        '''192.168.1.33
        '''192.168.1.34
        '''192.168.1.35
        '''192.168.1.36
        '''192.168.1.37
        '''192.168.1.38
        '''192.168.1.39
        '''192.168.1.40
        '''192.168.1.41
        '''192.168.1.42
        '''192.168.1.43
        '''192.168.1.44
        '''192.168.1.45
        '''192.168. [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property dhcp() As String
            Get
                Return ResourceManager.GetString("dhcp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        '''</summary>
        Friend ReadOnly Property Duh_Duh() As System.IO.UnmanagedMemoryStream
            Get
                Return ResourceManager.GetStream("Duh_Duh", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to License Key: B584D4C6CAA755473C06A3765E60E9C0F226D52DC7D322A69FF20BB99D71B825
        '''Clarity Serial Number: 14424911
        '''.
        '''</summary>
        Friend ReadOnly Property key() As String
            Get
                Return ResourceManager.GetString("key", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property NomiLogoBlue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("NomiLogoBlue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property telaid1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("telaid1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TSC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TSC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tyco() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tyco", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
